import Head from "next/head";
import Carousels from "../components/Carousel/Carousel";
import Welcome from "../components/Welcome/Welcome";
import Location from "../components/Location/Location";
import Coupon from "../components/Coupon/Coupon";
import Recommend from "../components/Recommend/Recommend";
import Instruction from "../components/Instruction/Instruction";
import Download from "../components/Download/Download";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luxstay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousels />
      <Welcome />
      <Location />
      <Coupon />
      <Recommend />
      <Instruction />
      <Download />
      <Footer />
    </div>
  );
}
