import { sanityClient, urlFor } from "../../sanity";
import groq from "groq";
import Link from "next/link";
import Head from "next/head";
import WordLimit from "react-word-limit";
import Filter from "../../components/Filter/Filter";
import styles from "../../styles/AllLocation.module.css";

export default function Location({ properties, pageSlug }) {
  return (
    <>
      <Head>
        <title>
          {properties.length} homestay tại {pageSlug}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Filter />
      <section className={styles.container}>
        <p>
          <b>
            Trước khi đặt phòng, hãy kiểm tra những địa điểm bị hạn chế du lịch
            trong thời gian này.
          </b>{" "}
          Sức khỏe và sự an toàn của cộng đồng luôn được đặt hàng đầu. Vì vậy,
          vui lòng làm theo chỉ thị của chính phủ bởi điều đó thực sự cần thiết.
        </p>
        <div className={styles.row}>
          <h2 style={{ fontSize: 25 }}>
            {properties.length} homestay tại {pageSlug}
          </h2>
          <div className={styles.input}>
            <input
              type="text"
              readOnly="readonly"
              autoComplete="off"
              placeholder="Lựa chọn"
              className={styles.elinput__inner}
            />
            <span className={styles.span}>Sắp xếp:</span>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              width="25px"
              className={styles.svg}
            >
              <path d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        </div>

        <div className={styles.allitem}>
          {properties.map((property, index) => {
            return (
              <Link href={`property/${property.slug.current}`}>
                <div className={styles.item__wrapper} location={pageSlug}>
                  <div key={index} className={styles.item}>
                    <img
                      src={urlFor(property.mainImage)}
                      alt=""
                      className={styles.item__image}
                    />
                    <p
                      style={{
                        fontSize: 14,
                        marginBottom: "5px",
                        color: "gray",
                      }}
                    >
                      {property.propertyType} - {property.bedrooms} phòng ngủ
                    </p>
                    <h4
                      style={{
                        fontSize: "1rem",
                        fontWeight: "normal",
                        marginBottom: "5px",
                      }}
                    >
                      <WordLimit limit={25}>{property.title}</WordLimit>
                    </h4>
                    <p style={{ fontSize: "0.875rem" }}>
                      <b>
                        {property.pricePerNight}
                        <u>đ</u>/đêm
                      </b>
                    </p>
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      </section>
    </>
  );
}

export async function getServerSideProps(pageContext) {
  const pageSlug = pageContext.query.location;
  const query = groq`*[ _type == "${pageSlug}"]`;
  const properties = await sanityClient.fetch(query);
  if (!properties.length) {
    return {
      props: {
        properties: [],
      },
    };
  } else {
    return {
      props: {
        properties,
        pageSlug,
      },
    };
  }
}
